enable ARC. set MacOSX base SDK to 10.7 and enable 10.6 compatibility
Using the MacOSX 10.6 SDK did not work because of these errors:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NSMutableOrderedSet", referenced from:
      objc-class-ref in libarclite_macosx.a(arclite.o)
  "_OBJC_CLASS_$_NSOrderedSet", referenced from:
      objc-class-ref in libarclite_macosx.a(arclite.o)
  "_objc_autoreleasePoolPush", referenced from:
      ___ARCLite__load in libarclite_macosx.a(arclite.o)
  "_objc_release", referenced from:
      _main in main.o
  "_objc_retain", referenced from:
      ___ARCLite__load in libarclite_macosx.a(arclite.o)
     (maybe you meant: _objc_retainedObject)
  "_objc_retainAutoreleasedReturnValue", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)

Linking to Foundation did not resolve this.

Disabling CLANG_LINK_OBJC_RUNTIME (Implicitly link Objective C Runtime
Support) also did not resolve this (it was disabled before).

Thus, the only option seemed to be to use SDK 10.7. Let's hope 10.6
compatibility works...